---
- name: anacondaの最新バージョンをインストールする
  shell: bash -lc "pyenv install anaconda3-5.3.0"
  become_user: vagrant
- name: pyenv rehash
  shell: bash -lc "pyenv rehash"
  become_user: vagrant
- name: pyenv global anaconda3-5.3.0
  shell: bash -lc "pyenv global anaconda3-5.3.0"
  become_user: vagrant
- name: anacondaをpythonのデフォルトに設定
  lineinfile:
    dest: /home/vagrant/.bashrc
    owner: vagrant
    group: vagrant
    line: "{{item}}"
  with_items:
    - 'export PATH="$PYENV_ROOT/versions/anaconda3-5.3.0/bin/:$PATH"'
- name: 環境変数の反映
  shell: bash -lc "source /home/vagrant/.bashrc"
  become_user: vagrant
- name: conda update conda
  shell: bash -lc "conda update conda"
  become_user: vagrant
